FROM node:24 AS build
WORKDIR /usr/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --check-files --network-concurrency 1
COPY . .
RUN yarn build

FROM node:24-slim
WORKDIR /usr/app
ENV NODE_ENV=production
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production --check-files --network-concurrency 1
COPY --from=build /usr/app/dist ./dist
COPY --from=build /usr/app/swagger.yaml ./swagger.yaml
CMD ["node", "dist/index.js"]
