apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: closecount-web-allow-ingress
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - closecount-client
          - closecount-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 8005
