apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: closecount
resources:
  - ../../base
  - mongo-pv.yaml
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - ingress.yaml
  - server-secret.yaml
images:
  - name: close-count-server
    newTag: dev
  - name: close-count-client
    newTag: dev
patches:
  - path: patch-server-env.yaml
  - path: patch-server-runtime.yaml
  - path: patch-client-env.yaml
  - path: patch-client-runtime.yaml
