apiVersion: v1
kind: PersistentVolume
metadata:
  name: closecount-mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/closecount-mongo
    type: DirectoryOrCreate
