apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: closecount-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: closecount-mongo-pv
