apiVersion: apps/v1
kind: Deployment
metadata:
  name: closecount-client
spec:
  template:
    spec:
      containers:
        - name: client
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          startupProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 60  # 5 minutes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
