apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: closecount-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - closecount.local
      secretName: closecount-tls
  rules:
    - host: closecount.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: closecount-server
                port:
                  number: 8005
          - path: /
            pathType: Prefix
            backend:
              service:
                name: closecount-client
                port:
                  number: 3000
