apiVersion: apps/v1
kind: Deployment
metadata:
  name: closecount-client
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: client
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
