name: Production script

on:
  push:
    branches: [ master ]

jobs:
  deploys:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install Nodejs and NPM
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          apt install nodejs
      - name: Install nodejs, npm and yarn
        run: |
          apt-get install yarn
          echo nodejs version
          node -v
          echo npm version
          npm -v
          echo yarn version
          yarn -v
 
