name: Close Count mern script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js ${{ matrix.node-version }} 
      working-directory: ./server
      run: yarn install
    - name: Install Reactjs
      working-directory: ./client
      run: yarn install
