name: Close Count mern script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} 
      working-directory: ./server
      run: yarn install && yarn start
    - name: User React.js
      working-directory: ./client
      run: yarn install && yarn start
