name: Production script

on:
  push:
    branches: [ master ]

jobs:
  deploys:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Deploying Close Count
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir projects 
            cd projects
            git clone git@github.com:phonist/close_count.git
            echo 'Close Count project cloned to host server'
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            Y
            apt install nodejs
            npm install --global yarn@1.22.10
            cd close_count/server
            pwd
            yarn install && yarn start
            cd ../client
            pwd 
            yarn install && yarn build && yarn add serve 
            yarn serve -s build 

