name: Production script

on:
  push:
    branches: [ master ]

jobs:
  deploys:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install server dependencies
        working-directory: ./server
        run: |
          sudo apt install nodejs=16.2.0
          yarn install
 
